// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Eventos.AcessoADados;
using System;

namespace Eventos.AcessoADados.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    [Migration("20180224140929_AdicionadoTableParticipante")]
    partial class AdicionadoTableParticipante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Eventos.AcessoADados.Modelos.Participante", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeParticipante")
                        .IsRequired();

                    b.Property<string>("EmailParticipante");

                    b.HasKey("IdEvento");

                    b.ToTable("Participante");

                    
                });
#pragma warning restore 612, 618
        }
    }
}
