// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Eventos.AcessoADados;
using System;

namespace Eventos.AcessoADados.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    [Migration("20180224140929_AdicionadoTableEventos")]
    partial class AdicionadoTableEventos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Eventos.AcessoADados.Modelos.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeEvento")
                        .IsRequired();

                    b.Property<DateTime>("DataEvento")
                        .IsRequired();

                    b.Property<string>("LocalEvento")
                        .IsRequired();

                    b.Property<DateTime>("HorarioInicio");

                    b.Property<DateTime>("HorarioFim");

                    b.Property<Boolean>("OpenBar");

                    b.Property<int>("QuantidadeAmbientes");

                    b.Property<string>("FaixaEtaria");

                    b.Property<int>("MaximoIngressos")
                        .IsRequired();

                    b.Property<int>("IngressosVendidos")
                        .IsRequired();

                    b.Property<string>("QuantidadeIngressos");

                    b.HasKey("IdEvento");

                    b.ToTable("Eventos");

                    
                });
#pragma warning restore 612, 618
        }
    }
}
